### ISSUE TITLE
& is necessary in order to indicate that the argument is a function

### ISSUE THREAD

**Issue by mendrugory** [tetiana12345678/elixir-flashcards#1]
Hi,

Thanks for the flashcards.

I have seen a mistake in the second [group of cards](https://github.com/tetiana12345678/elixir-flashcards/blob/master/02/elixircards2_a3.pdf) row 5 column 3. The function Stream.next_codepoint/1 needs a "&" in order to indicate that it is a function  =>  &Stream.next_codepoint/1.

Thanks and keep doing these things !!

**Comment by tetiana12345678** [comment]
@mendrugory, sorry for late response. Thanks for spotting it. I will push up correct version later on today. :)

**Comment by tetiana12345678** [comment]
@mendrugory corrected typo [here](https://github.com/tetiana12345678/elixir-flashcards/blob/master/02/elixircards2_a3.pdf). Thank you for your sharp eyes 👀
