### ISSUE TITLE
Provide flashcards as data

### ISSUE THREAD

**Issue by JordanAdams** [tetiana12345678/elixir-flashcards#4]
Hi 👋  

This is such a great idea and I'd love to hook this up as some kind of new tab page for myself. 

Is there any chance you might be able to provide the questions and answers in some kind of ingestible format such as JSON?

Example:
```
[
  {
    "question": "div(10,2)",
    "answer": "5",
    "difficulty": 1
  }
]
```

**Comment by tetiana12345678** [comment]
Hello @JordanAdams ✋ I've been thinking a lot about your suggestion. At the moment we are concentrating on building a shop for smoother order experience. Also, at the moment we are looking into coming up with the various games to play with cards and documenting various learning techniques to help mastering the subject :)

**Comment by michallepicki** [comment]
I would love to be able to import a deck package for Anki through [one of supported formats](https://apps.ankiweb.net/docs/manual.html#importing)

**Comment by tetiana12345678** [comment]
Hi @michallepicki,
The curation for content of our cards takes a lot of time and effort and forms the foundation of our product, so we don't plan to open source the content, however we are happy to share the digital version of our content with our customers for their own use, so if you've already purchased any of the packs, let me know, and I'll be happy to work with you on that.
We are building (slowly in our spare time) a platform to provide a digital flashcard experience. I can't say when it will be ready, but follow us on twitter for updates @elixircards.
👍
