### ISSUE TITLE
Typos in the elixircards2_back_a3

### ISSUE THREAD

**Issue by nickgnd** [tetiana12345678/elixir-flashcards#5]
Hi @tetiana12345678 and thanks for this project :)

In the 'elixircards2_back_a3.pdf' the first card on the left in the last row has two typos.

"empty list doesn't have have head and tale"

- "have" is repeated two times
- "tale" instead of 'tail'

Bye bye :)

**Comment by tetiana12345678** [comment]
Updated pdf to include cards from `fundamentals 1`, which have been tested, before pdf got generated 😄
